spring.application.name=Lab4
# Puerto desde variable de entorno (12-factor)
server.port=${PORT:5000}

# SSL
server.ssl.key-store-type=PKCS12
server.ssl.key-store=${KEY_STORE_PATH:classpath:keystore/ecikeystore.p12}
server.ssl.key-store-password=${KEY_STORE_PASSWORD:123456}
server.ssl.key-alias=${KEY_ALIAS:ecikeypair}
server.ssl.enabled=true

# H2
spring.datasource.url=jdbc:h2:mem:securedb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop